### ISSUE TITLE
Confusion over the dependence loss (dloss)

### ISSUE THREAD

**Issue by chunchet-ng** [Ugenteraan/Deep_Hierarchical_Classification#5]
Hi there,

Based on [this line](https://github.com/Ugenteraan/Deep_Hierarchical_Classification/blob/e4f20ae51a2daabfc1c01f6fdab778ef31cc7617/model/hierarchical_loss.py#L73) of your dloss, why is the product of ploss subtracted by 1 (-1), shouldn't it be multiplied by -1? 

In the paper, equation 6 of dloss is -1 * ploss_l-1 * ploss_l. Please correct me if I am wrong.

Thank you.

**Comment by Ugenteraan** [comment]
Hi @chunchet-ng ,

I'm glad you asked. I believe the authors might have had a typo or mistakenly used the -1 term there. This is because if we multiply the loss function with a -1, the entire d_loss would be in a negative value regardless of the constant value, p_loss when the model predicted the classes in wrong hierarchical orders. We definitely do not want this to be the case as we want to penalize the model when the hierarchical order is wrong. That's why I removed the multiplication by -1. The subtraction by 1 was arbitrary. You can remove it and it'll still work fine. If you think my justification is wrong, please do correct me.

Cheers!
